name: Challenge1
on: workflow_disptach

jobs:
    job1:
        name: job1
        runs-on: ubuntu-latest
        steps:
        - name: step1
          run: |
           echo "Hello from job1"
           date
           pwd
           ls -l
    job2:
        name: job2
        runs-on: ubuntu-latest
        steps:
        - name: setup-python
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"
        - name: step1 check python --version
          run: python --version
        - name: step2 set up pandas
          run: |
            pip install pandas
            pip --version
        - name: step3 create artifact
          run: | 
           touch artifact.py
           echo "# This is my python artifact" > artifact.py
           python artifact.py




