name: tutorail1
on: push  

jobs:
    job1:
         name: job1
         runs-on: ubuntu-latest
         steps:
         - name: setup python
           uses: actions/setup-python@v4
           with:
            python-version: 3.9
         - name: check python --version
           run: python --version
    job2:
         name: job2
         runs-on: windows-latest
         steps:
         - name: step2
           run: echo " Hello from job2"
    job3:
        name: job3
        runs-on: ubuntu-latest
        steps:
        - name: step3
          run: echo "Hello from job3"
    job4:
        name: job4
        needs: [job1,job2]
        runs-on: ubuntu-latest
        steps:
        - name: step4
          run: echo "This is job4"